version: "3"

services:
  setup_rsyslog:
    #image: mbixtech/rsyslog:${TAG}
    image: ubuntu:18.04
    container_name: setup_rsyslog
    user: root
    command: ['/bin/bash', '-c', 'touch /log/syslog.log; chown -R 1000.1000 /log; find /log -ls']
    volumes:
      - ./log:/log
