version: "3"

services:
  rsyslog:
    image: mbixtech/rsyslog:${TAG}
    hostname: rsyslog
    environment:
      - TZ=${TZ}
    ports:
      - "1514:514"
      - "1514:514/udp"
    volumes:
      - ./rsyslog.d:/etc/rsyslog.d
      - ./log:/log
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

